#define PROJ_SCREENMODE TASMODE
#define PROJ_FPS 255
#define PROJ_HIGH_RAM HIGH_RAM_MUSIC
#define PROJ_ENABLE_SOUND 1
#define PROJ_ENABLE_SFX
#define PROJ_ENABLE_SD_MUSIC
#define PROJ_AUD_FREQ 22050
#define PROJ_STREAM_LOOP 1
#define PROJ_ENABLE_SYNTH 0
#define PROJ_MAX_SPRITES 16
#define PROJ_TILE_H 1
#define PROJ_TILE_W 1
#define PROJ_DEVELOPER_MODE 0
#define MAX_TILE_COUNT 16
#define PROJ_LINE_FILLERS TAS::NOPFiller, TAS::NOPFiller, TAS::NOPFiller, TAS::NOPFiller, TAS::NOPFiller
